#!/usr/bin/env python3

#            ---------------------------------------------------
#                             Utopia Framework                  
#            ---------------------------------------------------
#                  Copyright (C) <2020>  <Entynetproject>       
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#        but WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#        GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os

os.system("printf '\033]2;Utopia Framework\a'")

import sys
import subprocess
import readline
import time

I = '\033[1;77m[i] \033[0m'
Q = '\033[1;77m[?] \033[0m'
G = '\033[1;34m[*] \033[0m'
S = '\033[1;32m[+] \033[0m'
W = '\033[1;33m[!] \033[0m'
E = '\033[1;31m[-] \033[0m'

readline.parse_and_bind("tab: complete")

def banner():
    os.system("clear")
    os.system("cat banner/banner.txt")
    print("")
    print("Utopia Framework v1.0")
    print("------------------------")
    print("")

def main():
    location = []
    pwd = 0
    rhost = ""
    rport = ""
    cmd = "uname -a"
    ui = input('\033[4mutopia\033[0m> ').strip(" ")
    ui = ui.split()
    while True:
        if ui == []:
            pass
        elif ui[0] == "exit":
            sys.exit()
        elif ui[0] == "clear":
            os.system("clear")
        elif ui[0] == "update":
            os.system("chmod +x etc/update.sh && etc/update.sh")
        elif ui[0] == "help":
            print("")
            print("Core Commands")
            print("=============")
            os.system("cat data/cmds/core_cmds.txt")
            print("")
        elif ui[0] == "modules":
            print("")
            print("Modules")
            print("=======")
            os.system("cat data/modules/modules.txt")
            print("")
        elif ui[0] == "use":
            if len(ui) < 2:
                print("Usage: use <module>")
            else:
                attack = ui[1]
                if attack == "libssh_rce_noauth" or attack == "libssh_shell_noauth":
                    location.append('')
                    location[pwd] = ui[1]
                    mod = input('\033[4mutopia\033[0m(\033[1;31m'+location[pwd]+'\033[0m)> ').strip(" ")
                    mod = mod.split()
                    while True:
                        if mod == []:
                            pass
                        elif mod[0] == "back":
                            pwd -= 1
                            location = location[0:-1]
                            if location == []:
                                pwd = 0
                                break
                        elif mod[0] == "set":
                            if len(mod) < 3:
                                print("Usage: set <option> <value>")
                            else:
                                if location[pwd] == "libssh_rce_noauth":
                                    if mod[1].lower() == "rhost":
                                        rhost = mod[2]
                                        print(I + "RHOST ==> " + mod[2])
                                    elif mod[1].lower() == "rport":
                                        rport = mod[2]
                                        print(I + "RPORT ==> " + mod[2])
                                    elif mod[1].lower() == "cmd":
                                        cmd = mod[2]
                                        print(I + "CMD ==> " + mod[2])
                                    else:
                                        print(E+"Options is not found!")
                                else:
                                    if mod[1].lower() == "rhost":
                                        rhost = mod[2]
                                        print(I + "RHOST ==> " + mod[2])
                                    elif mod[1].lower() == "rport":
                                        rport = mod[2]
                                        print(I + "RPORT ==> " + mod[2])
                                    else:
                                        print(E+"Options is not found!")
                        elif mod[0] == "options":
                            if location[pwd] == "libssh_rce_noauth":
                                if rhost == "":
                                    rhost = "none"
                                if rport == "":
                                    rport = "none"
                                if cmd == "":
                                    cmd = "none"
                                os.system("ruby data/options/options.rb libssh_rce_noauth "+rhost+" "+rport+" '"+cmd+"'")
                            else:
                                if rhost == "":
                                    rhost = "none"
                                if rport == "":
                                    rport = "none"
                                os.system("ruby data/options/options.rb libssh_shell_noauth "+rhost+" "+rport)
                        elif mod[0] == "use":
                            if len(mod) < 2:
                                print("Usage: use <module>")
                            else:
                                attack = mod[1]
                                if attack == "libssh_rce_noauth" or attack == "libssh_shell_noauth":
                                    location.append('')
                                    pwd += 1
                                    location[pwd] = mod[1]
                                    rhost = ""
                                    rport = ""
                                    cmd = ""
                                else:
                                    print(E+"Module is not found!")
                        elif mod[0] == "run":
                            if rhost == "" or rport == "":
                                print(E+"Target is not specified!")
                            else:
                                if location[pwd] == "libssh_rce_noauth":
                                    if cmd == "":
                                        print(E+"Command for RCE is not specified!")
                                    else:
                                        print(G+"Starting libssh_rce_noauth attack...")
                                        os.system("python3 core/exploit.py "+rhost+" -p "+rport+" -v '"+cmd+"'")
                                elif attack == "libssh_shell_noauth":
                                    print(G+"Starting libssh_shell_noauth attack...")
                                    os.system("python3 core/exploit.py "+rhost+" -p "+rport+" -v --shell")
                        elif mod[0] == "clear":
                            os.system("clear")
                        elif mod[0] == "exit":
                            sys.exit()
                        elif mod[0] == "update":
                            os.system("chmod +x etc/update.sh && etc/update.sh")
                        elif mod[0] == "help":
                            print("")
                            print("Core Commands")
                            print("=============")
                            os.system("cat data/cmds/core_cmds.txt")
                            print("")
                            print("Module Commands")
                            print("===============")
                            os.system("cat data/cmds/module_cmds.txt")
                            print("")
                        else:
                            print(E+"Unrecognized command!")
                        mod = input('\033[4mutopia\033[0m(\033[1;31m'+location[pwd]+'\033[0m)> ').strip(" ")
                        mod = mod.split()
                else:
                    print(E+"Module is not found!")
        else:
            print(E+"Unrecognized command!")
        ui = input('\033[4mutopia\033[0m> ').strip(" ")
        ui = ui.split()
        
banner()
main()
